#!/usr/bin/env bash
# Copyright (c) 2025 b-data GmbH.
# Copyright (c) 2023 Microsoft Corporation.
# Distributed under the terms of the MIT License.
#
# Modified by b-data for seamless use with Dev Containers.
#
# https://code.visualstudio.com/remote/advancedcontainers/sharing-git-credentials

set -e

if [ "$(command -v ssh-agent)" ]; then
  if [ -z "$SSH_AUTH_SOCK" ]; then
    # Check for a currently running instance of the agent
    RUNNING_AGENT="$(pgrep -f 'ssh-agent -s' | wc -l | tr -d '[:space:]')"
    if [ "$RUNNING_AGENT" = "0" ]; then
      mkdir -p -m 0700 "$HOME/.ssh"
      # Launch a new instance of the agent
      ssh-agent -s &> "$HOME/.ssh/ssh-agent"
    fi
    eval "$(cat "$HOME/.ssh/ssh-agent")" > /dev/null
  fi
  ssh-add 2> /dev/null
fi
